# Generated by Django 2.1.2 on 2018-10-28 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudad',
            },
        ),
        migrations.CreateModel(
            name='GeneroP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generoP', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Genero Persona',
                'verbose_name_plural': 'Genero Persona',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=80)),
                ('run', models.IntegerField()),
                ('nombreP', models.CharField(max_length=80)),
                ('telefono', models.IntegerField()),
                ('fechaN', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=80)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GeneroP')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreR', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Region',
            },
        ),
        migrations.CreateModel(
            name='tipoVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreV', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo Vivienda',
                'verbose_name_plural': 'Tipo Vivienda',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipoV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoVivienda'),
        ),
    ]
